### ISSUE TITLE
Bot no longer betting

### ISSUE THREAD

**Issue by Leurus** [Pauan/SaltyBetBot#6] opened 2019-03-04 10:11 UTC
The bot stopped betting a day or two ago, I'm not sure why because literally nothing has changed, it simply stopped working. Tried doing an update but it says it's already up to date. The chat tab opens, but the records and chart page stay on "loading" indefinitely. I'm guessing something with the update for salty illuminati is causing it?

**Comment by Pauan** [comment] 2019-03-04 15:09
Everything works fine for me.

I assume you've restarted Chrome, and also closed/reopened the SaltyBet tab?

What's your Chrome version?

**Comment by Leurus** [comment] 2019-03-04 15:40
Yes, of course I've restarted Chrome several times, closed/re-opened SaltyBet, logged in and out several times, etc. Using Chrome 72, the most recent version.

Like I said, I think it's because of the fact I'm illuminati. Something may have broke after you fixed the tournament betting issue for illuminati.

**Comment by Leurus** [comment] 2019-03-04 15:42
Here's a screenshot of errors I'm getting if it helps:
https://i.imgur.com/E89gSYI.png

**Comment by Pauan** [comment] 2019-03-04 23:36
Yeah, that helps.

In the `chrome://extensions/` page, could you click the `Inspect views  background page` link, then copy-paste everything into here?

**Comment by Leurus** [comment] 2019-03-05 01:22
Finished loading Rust wasm module 'background'
background.js:564 2019-03-04T23:33:19.755Z [src\bin\background\main.rs:255] Initializing...
background.js:564 2019-03-04T23:33:19.780Z [src\bin\background\main.rs:257] Initializing database took 25.220000185072422ms
background.js:564 2019-03-04T23:33:22.898Z [src\bin\background\main.rs:273] Inserted 0 records
background.js:564 2019-03-04T23:33:22.908Z [src\bin\background\main.rs:263] Inserting default records took 3127.4699999485165ms
background.js:564 2019-03-04T23:33:22.908Z [src\bin\background\main.rs:381] Background page started
background.js:663 Uncaught TypeError: Message length exceeded maximum allowed length.
    at __cargo_web_snippet_ffa8ae2a271a4282450c794114323b757cee4897 (background.js:663)
    at _ZN13salty_bet_bot10on_message28_$u7b$$u7b$closure$u7d$$u7d$28_$u7b$$u7b$closure$u7d$$u7d$7snippet17h78935e038f754328E (wasm-function[347]:5)
    at _ZN80_$LT$std..future..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$4poll17h1641a655114cb299E (wasm-function[274]:7430)
    at _ZN12futures_core6future10future_obj6if_std129_$LT$impl$u20$futures_core..future..future_obj..UnsafeFutureObj$LT$$u27$a$C$$u20$T$GT$$u20$for$u20$alloc..boxed..Box$LT$F$GT$$GT$4poll17h6fe5fd2c3df72a81E.llvm.16051464054983307168 (wasm-function[178]:5)
    at _ZN6stdweb7webcore8executor14EventLoopQueue5drain17hd8d97adff09bf495E (wasm-function[508]:491)
    at _ZN193_$LT$stdweb..webcore..newtype..Newtype$LT$$LP$stdweb..webcore..serialization..FunctionTag$C$$u20$$LP$$RP$$RP$$C$$u20$F$GT$$u20$as$u20$stdweb..webcore..serialization..FuncallAdapter$LT$F$GT$$GT$15funcall_adapter17h88982437b3fbb899E (wasm-function[538]:384)
    at Object.Module.STDWEB_PRIVATE.dyncall (background.js:474)
    at output (background.js:174)
    at MutationObserver.wrapper (background.js:579)

**Comment by Pauan** [comment] 2019-03-09 01:39
I think I know what's causing this, but it's really difficult to fix. I'm working on it.

**Comment by Leurus** [comment] 2019-03-10 01:10
Thanks for the update.

**Comment by Leurus** [comment] 2019-03-25 04:09
Any way to roll back to a previous working version? I've missed almost a month of bets and records, so at this point I'll take whatever I can get just to keep my records continuous.

**Comment by Pauan** [comment] 2019-03-25 10:17
Yeah, there is: run `git checkout 1c301a3fdd83291e8303294c07d5f0d40d551b2a` and then Reload the extension in `chrome://extensions/`

However, I don't think that will fix the problem for you, because I believe the problem is caused by having too many records (which then causes Chrome to get overloaded), so you'll still have the same problem.

I have also been collecting records, and when I release a new version my records will get merged with your records, so all is not lost.

**Comment by Pauan** [comment] 2019-03-25 11:45
(That's why it's difficult to fix, because I have to workaround a bug/limitation in Chrome itself.)

**Comment by Leurus** [comment] 2019-03-25 15:52
Yeah you're right, changing versions didn't fix anything. That indeed sounds like a very difficult problem to fix. Any ideas so far on how it could be addressed?

**Comment by Pauan** [comment] 2019-03-25 19:47
My current plan is to change it so that it sends the records in multiple chunks, rather than in one message. But that requires some significant changes, and it also requires this issue to get fixed first: https://github.com/rust-lang-nursery/futures-rs/issues/1489

**Comment by Pauan** [comment] 2019-04-29 01:04
Sorry for the delay on this, https://github.com/rust-lang-nursery/futures-rs/issues/1489 finally got (temporarily) fixed.

I tried to workaround this issue by sending the records in multiple chunks. Please [update to the latest version](https://github.com/Pauan/SaltyBetBot#how-to-upgrade) and let me know if it fixes it.

**Comment by Leurus** [comment] 2019-08-15 01:54
Hey Pauan, just updated and it's still not betting. It also isn't exporting my records at all, it just stays frozen on "loading" indefinitely. I've tried updating chrome, re-updating the extension and restarting Chrome to no avail. I can try completely re-installing the extension if you're able to update the records?

**Comment by Pauan** [comment] 2019-08-15 12:02
@Leurus Please follow these directions:

1. Go to `chrome://extensions/`

2. Find `Salty Bet Bot` and click on the `background page` blue link.

3. Go to the "Console" tab, then copy-paste everything in there so I can see it.

**Comment by Pauan** [comment] 2019-08-15 12:04
(Also, if there is a red "Errors" button for `Salty Bet Bot`, click on it and take some screenshots of that too)

**Comment by Leurus** [comment] 2019-08-15 12:54
Uncaught TypeError: Message length exceeded maximum allowed length.
    at __extjs_0f83fef10ad7b0a50ad379842d01fe04c07a7b04 (background.js:630)
    at _$LT$std..future..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::hc3632d0d9c73d972 (wasm-function[305]:6159)
    at _$LT$alloc..boxed..Box$LT$F$GT$$u20$as$u20$futures_core..future..future_obj..UnsafeFutureObj$LT$$u27$a$C$$u20$T$GT$$GT$::poll::h431b093297301f18 (wasm-function[129]:5)
    at stdweb::webcore::executor::EventLoopQueue::drain::hd1fb7bba8ce4c71e (wasm-function[510]:492)
    at _$LT$stdweb..webcore..newtype..Newtype$LT$$LP$stdweb..webcore..serialization..FunctionTag$C$$u20$$LP$$RP$$RP$$C$$u20$F$GT$$u20$as$u20$stdweb..webcore..serialization..FuncallAdapter$LT$F$GT$$GT$::funcall_adapter::h3bd8ce82b87d57f4 (wasm-function[531]:357)
    at Object.Module.STDWEB_PRIVATE.dyncall (background.js:474)
    at output (background.js:174)
    at MutationObserver.wrapper (background.js:642)

**Comment by Leurus** [comment] 2019-08-15 12:57
![image](https://user-images.githubusercontent.com/26194213/63095968-8f052c00-bf3a-11e9-8ccd-4165e394ad5c.png)
![image](https://user-images.githubusercontent.com/26194213/63095998-a3492900-bf3a-11e9-8073-51ad56e0b849.png)
![image](https://user-images.githubusercontent.com/26194213/63096014-b1974500-bf3a-11e9-8b06-163d3a83805c.png)

**Comment by Pauan** [comment] 2019-08-15 13:35
You're sure that you followed **all** of [the upgrade steps](https://github.com/Pauan/SaltyBetBot#how-to-upgrade), including the `git pull`?

**Comment by Leurus** [comment] 2019-08-15 13:40
Yes, Here's a screenshot of what I did to update:

![image](https://user-images.githubusercontent.com/26194213/63098352-bbbc4200-bf40-11e9-9a65-a403742cc7dc.png)

**Comment by Pauan** [comment] 2019-08-15 13:42
Okay, so that means the `git pull` failed, which means it didn't update. It seems you mucked around with your git repo in some way.

So you need to do `git checkout master` and then do `git pull`, and then follow the rest of the instructions.

**Comment by Pauan** [comment] 2019-08-15 13:46
Ah, I see, earlier I had said to do `git checkout 1c301a3fdd83291e8303294c07d5f0d40d551b2a` to revert to the old version, and that's what caused the issue, so this was my fault, sorry about that.

**Comment by Leurus** [comment] 2019-08-15 13:48
Looks to be working now. Thanks!

I presume the update from 2 hours ago includes a records update that I now have also? If so, much appreciated.

**Comment by Pauan** [comment] 2019-08-15 13:49
Yes, the latest records have been pushed, so you should have them now.

Since this is fixed, I'll go ahead and close this, thanks for letting me know it's working now!

**Closed by Pauan** 2019-08-15 13:49 UTC
